wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
alpha_val:
  desc: null
  value: 1.0
auto_lr:
  desc: null
  value: false
auxnetwork:
  desc: null
  value: base_reg
batch_size:
  desc: null
  value: 64
beta_val:
  desc: null
  value: 0.0005
bidirectional:
  desc: null
  value: true
dataset:
  desc: null
  value: TAPE
dev:
  desc: null
  value: false
embedding_dim:
  desc: null
  value: 100
eta_val:
  desc: null
  value: 0.001
gamma_val:
  desc: null
  value: 1.0
hidden_dim:
  desc: null
  value: 200
hparams/alpha_val:
  desc: null
  value: 1.0
hparams/auto_lr:
  desc: null
  value: false
hparams/auxnetwork:
  desc: null
  value: base_reg
hparams/batch_size:
  desc: null
  value: 64
hparams/beta_val:
  desc: null
  value: 0.0005
hparams/bidirectional:
  desc: null
  value: true
hparams/dataset:
  desc: null
  value: TAPE
hparams/dev:
  desc: null
  value: false
hparams/embedding_dim:
  desc: null
  value: 100
hparams/eta_val:
  desc: null
  value: 0.001
hparams/gamma_val:
  desc: null
  value: 1.0
hparams/hidden_dim:
  desc: null
  value: 200
hparams/input_dim:
  desc: null
  value: 22
hparams/interp_samp:
  desc: null
  value: true
hparams/interp_size:
  desc: null
  value: 16
hparams/interp_weight:
  desc: null
  value: 0.001
hparams/kernel_size:
  desc: null
  value: 4
hparams/latent_dim:
  desc: null
  value: 30
hparams/layers:
  desc: null
  value: 6
hparams/linformer_k:
  desc: null
  value: 60
hparams/log_dir:
  desc: null
  value: None
hparams/lr:
  desc: null
  value: 2.0e-05
hparams/n_epochs:
  desc: null
  value: 400
hparams/n_gpus:
  desc: null
  value: 1
hparams/neg_floor:
  desc: null
  value: -2.0
hparams/neg_focus:
  desc: null
  value: false
hparams/neg_norm:
  desc: null
  value: 4.0
hparams/neg_samp:
  desc: null
  value: true
hparams/neg_size:
  desc: null
  value: 16
hparams/neg_weight:
  desc: null
  value: 0.8
hparams/probs:
  desc: null
  value: 0.2
hparams/project_name:
  desc: null
  value: relso_project
hparams/reg_ramp:
  desc: null
  value: false
hparams/seq_len:
  desc: null
  value: 237
hparams/seqdist_cutoff:
  desc: null
  value: None
hparams/sigma_val:
  desc: null
  value: 1.5
hparams/task:
  desc: null
  value: recon
hparams/use_linformer:
  desc: null
  value: true
hparams/vae_ramp:
  desc: null
  value: true
hparams/wl2norm:
  desc: null
  value: false
input_dim:
  desc: null
  value: 22
interp_samp:
  desc: null
  value: true
interp_size:
  desc: null
  value: 16
interp_weight:
  desc: null
  value: 0.001
kernel_size:
  desc: null
  value: 4
latent_dim:
  desc: null
  value: 30
layers:
  desc: null
  value: 6
linformer_k:
  desc: null
  value: 60
log_dir:
  desc: null
  value: None
lr:
  desc: null
  value: 2.0e-05
n_epochs:
  desc: null
  value: 400
n_gpus:
  desc: null
  value: 1
neg_floor:
  desc: null
  value: -2.0
neg_focus:
  desc: null
  value: false
neg_norm:
  desc: null
  value: 4.0
neg_samp:
  desc: null
  value: true
neg_size:
  desc: null
  value: 16
neg_weight:
  desc: null
  value: 0.8
probs:
  desc: null
  value: 0.2
project_name:
  desc: null
  value: relso_project
reg_ramp:
  desc: null
  value: false
seq_len:
  desc: null
  value: 0
seqdist_cutoff:
  desc: null
  value: None
sigma_val:
  desc: null
  value: 1.5
task:
  desc: null
  value: recon
use_linformer:
  desc: null
  value: true
vae_ramp:
  desc: null
  value: true
wl2norm:
  desc: null
  value: false
